# Generated by Django 5.1.4 on 2025-04-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditAuxTxLog',
            fields=[
                ('id_audit_aux_tx_log', models.AutoField(primary_key=True, serialize=False)),
                ('id_transaccion', models.IntegerField(blank=True, null=True)),
                ('nom_tabla', models.CharField(blank=True, max_length=64, null=True)),
                ('audit_type', models.CharField(blank=True, max_length=1, null=True)),
                ('id_audit', models.IntegerField(blank=True, null=True)),
                ('rollbacked', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'audit_aux_tx_log',
                'ordering': ['-created_on'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablaAuditada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('columnas', models.IntegerField(default=0)),
                ('audit_activa', models.BooleanField(default=False)),
                ('trigger_insert', models.BooleanField(default=False)),
                ('trigger_update', models.BooleanField(default=False)),
                ('trigger_delete', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tabla auditada',
                'verbose_name_plural': 'Tablas auditadas',
            },
        ),
    ]
