# Generated by Django 5.1.4 on 2025-07-05 17:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditAuxTxLog',
            fields=[
                ('id_audit_aux_tx_log', models.AutoField(primary_key=True, serialize=False)),
                ('id_transaccion', models.IntegerField(blank=True, null=True)),
                ('nom_tabla', models.CharField(blank=True, max_length=64, null=True)),
                ('audit_type', models.CharField(blank=True, max_length=1, null=True)),
                ('id_audit', models.IntegerField(blank=True, null=True)),
                ('rollbacked', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'audit_aux_tx_log',
                'ordering': ['-created_on'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InformeAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=50)),
                ('generado_por', models.CharField(max_length=100)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('resumen', models.TextField()),
                ('datos', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=64)),
                ('tabla', models.CharField(blank=True, max_length=64, null=True)),
                ('mensaje', models.TextField()),
                ('nivel', models.CharField(max_length=16)),
                ('detalles', models.JSONField(blank=True, null=True)),
                ('visible_para', models.CharField(choices=[('auditor', 'Auditor'), ('admin', 'Administrador')], default='admin', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='TablaAuditada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('columnas', models.IntegerField(default=0)),
                ('audit_activa', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('trigger_insert', models.BooleanField(default=False)),
                ('trigger_update', models.BooleanField(default=False)),
                ('trigger_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tabla auditada',
                'verbose_name_plural': 'Tablas auditadas',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('AUDITOR', 'Auditor'), ('LECTOR', 'Lector')], default='LECTOR', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
