# Generated by Django 5.1.4 on 2025-05-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=50)),
                ('generado_por', models.CharField(max_length=100)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('resumen', models.TextField()),
                ('datos', models.JSONField()),
            ],
        ),
    ]
