# Generated by Django 5.1.4 on 2025-06-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=64)),
                ('tabla', models.CharField(blank=True, max_length=64, null=True)),
                ('mensaje', models.TextField()),
                ('nivel', models.CharField(max_length=16)),
                ('detalles', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
