# Generated by Django 5.1.4 on 2025-06-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_systemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='visible_para',
            field=models.CharField(choices=[('auditor', 'Auditor'), ('admin', 'Administrador')], default='admin', max_length=16),
        ),
    ]
